name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: Run SonarCloud Analysis
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install SonarCloud Scanner
        run: |
          choco install sonarqube-scanner

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Utilisation du secret SONAR_TOKEN
        run: |
          sonar-scanner -Dsonar.projectKey=flask_project \
                        -Dsonar.organization=your-organization-key \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=https://sonarcloud.io \
                        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Run tests
        run: |
          pytest -v
